### ISSUE TITLE
有些歌曲下载不下来

### ISSUE THREAD

**Issue by fs1314** [God-2077/python-code#3]
比如歌曲id4044366（Ten Little Indians），包含在歌单里面的时候下载不下来

**Comment by God-2077** [comment]
这歌，额，太短了（45秒），程序直接判定为试听歌曲了，然后删了~~~

**Comment by fs1314** [comment]
> 这歌，额，太短了（45秒），程序直接判定为试听歌曲了，然后删了~~~

可以关闭屏蔽吗？在哪关？

**Comment by God-2077** [comment]
已更新 
最新版：[v.24-10-06](https://github.com/God-2077/python-code/blob/main/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%AD%8C%E5%8D%95%E6%89%B9%E9%87%8F%E4%B8%8B%E8%BD%BD%E6%AD%8C%E6%9B%B2/v.24-10-06.py)

**Comment by God-2077** [comment]
![image](https://github.com/user-attachments/assets/7b80f63a-7e30-4bc1-979c-09d42c5c773e)
填 yes 即可
